A = float(input("Veuillez entrer la valeur de A : "))
B = float(input("Veuillez entrer la valeur de B : "))
S = A + B
P = A * B
Df = A - B
Dv = A / B 
print("A + B  = ",S)
print("A * B  = ",P)
print("A - B  = ",Df)
print("A / B  = ",Dv)